apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drova-staging
resources:
  - ../../base
  - config/app-config.yaml
  - config/httproute.yaml
  - sealed-secrets/sealed-secret-app.yaml
  - sealed-secrets/sealed-secret-pg-app-creds.yaml
  - sealed-secrets/sealed-secret-pg-users-creds.yaml
  - sealed-secrets/sealed-secret-pg-trips-creds.yaml
  - sealed-secrets/sealed-secret-pg-payments-creds.yaml
  - sealed-secrets/sealed-secret-redis.yaml
images:
  - name: ghcr.io/tim275/drova/api-gateway
    newTag: v0.21.0
    digest: sha256:c3e69a89c20fbf0707904c05966015eae5687f875ab58f9c8859d773b616a9ed
  - name: ghcr.io/tim275/drova/user-service
    newTag: v0.21.0
    digest: sha256:8d81a0f0ce64336854beae9948a97d92b0ceff6f18d299d3927aec18e06fdb17
  - name: ghcr.io/tim275/drova/trip-service
    newTag: v0.21.0
    digest: sha256:e8cebedd1960bcea1bdbf0126b8be2078b3abbc0dde13a62ffc6527a775ff512
  - name: ghcr.io/tim275/drova/driver-service
    newTag: v0.21.0
    digest: sha256:8526972adaf987208d095ffb33af577a681f09682a8a480ab488cb6fc92cce46
  - name: ghcr.io/tim275/drova/payment-service
    newTag: v0.21.0
    digest: sha256:111f593665bc106530dbbd0abcc84cfd4c0c99537fbc929038fe01289f9b5f85
  - name: ghcr.io/tim275/drova/chat-service
    newTag: v0.21.0
    digest: sha256:5e5d34d82e57be224bd90172da1f96ef0453e038031861202bc868c29c708900
  - name: ghcr.io/tim275/drova/frontend
    newTag: v0.21.0
    digest: sha256:c428259adf53d0ae40e17f1a38d4b14cc8caf6298fd026fb224f415c4e473424
commonLabels:
  app.kubernetes.io/name: drova
  app.kubernetes.io/part-of: drova
  environment: staging
  team: timour
