apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drova-staging
resources:
  - ../../base
  - config/app-config.yaml
  - config/httproute.yaml
  - sealed-secrets/sealed-secret-app.yaml
  - sealed-secrets/sealed-secret-pg-app-creds.yaml
  - sealed-secrets/sealed-secret-pg-users-creds.yaml
  - sealed-secrets/sealed-secret-pg-trips-creds.yaml
  - sealed-secrets/sealed-secret-pg-payments-creds.yaml
  - sealed-secrets/sealed-secret-redis.yaml
images:
  - name: ghcr.io/tim275/drova/api-gateway
    newTag: v0.20.0
    digest: sha256:45e91c388278920705124394251713448b768c93654ceb47169f7b3779fe4701
  - name: ghcr.io/tim275/drova/user-service
    newTag: v0.20.0
    digest: sha256:0ba059936669e82f485cc0e58dc3f8bed29b910d00931b98d8091b1e2cda45b8
  - name: ghcr.io/tim275/drova/trip-service
    newTag: v0.20.0
    digest: sha256:ba864ea0ce83cb1adb38e64384498a3f2cca977345fd00e2dcf669a3637c3959
  - name: ghcr.io/tim275/drova/driver-service
    newTag: v0.20.0
    digest: sha256:0c21f39ba33094c0c17535c482b025c6b942aaf2ab8990d2ce50f824a511273f
  - name: ghcr.io/tim275/drova/payment-service
    newTag: v0.20.0
    digest: sha256:da8992322b0a06e7b3db19da8269d0fe94fd8dc0b5fa02cbde41877281a8cbfe
  - name: ghcr.io/tim275/drova/chat-service
    newTag: v0.20.0
    digest: sha256:016bcd9777e6273bca5387aee3171de5a8c1bcaf561db609d50e28ece945c80f
  - name: ghcr.io/tim275/drova/frontend
    newTag: v0.20.0
    digest: sha256:c428259adf53d0ae40e17f1a38d4b14cc8caf6298fd026fb224f415c4e473424
commonLabels:
  app.kubernetes.io/name: drova
  app.kubernetes.io/part-of: drova
  environment: staging
  team: timour
