---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drova-kafka-secrets
  namespace: drova
spec:
  encryptedData:
    KAFKA_SASL_PASSWORD: AgANyc5jZTeQkhTu3Bz7Qa6DF+LAuJDzXQiYahmW5bFaZITFbPadgNznmwykn92lYEgllVcPQKyeuTTmyVAW6gZEgMvhlomYQfq0HG0NchwbkqUEILnnRfoARkEmlE1HmXN0+cOh2hGZZXbHTr0TvQqu60q+N7DoI2wdWbwvX8sHiMHRyD3TFuR91pgAKJNik2vM1H8PYi5ymcc7eLuusm35sCaOZK4HHk35O01XXZJTJbcl60qT2llPfEXA4V4h9sb1tNH6VpIETY24ksrEBQ4lmBlkxdcRmZeWPl/uo+wYr+vJ+oFIzwTkeyeEUhzbEALtSNMJLpu+z4M3VPflnUPgt5DDbfLiWNhMAITeOGuhrNxNDggZfN/XI1Ed/o5siSOiTCXG61gcgV8Jiw7ShhPXNpn7/BhCELJPnNQAg6HBXEYiIS225wYYsmkHbAXcz7As4hy++Vivn6ujoGSQLKNhy/D4CL6MdodXUPrbMukahN5i1vDnQKOh+d0wv3uDt0kH+RXjxuocH3dWHx/2MQeeanIw/GMg3UQoBiHHo7VYNnyWMxU1Z/1UjAyrYY0L/wASHjeihNDpTMhGmcBgvHKyACLa5y2rXm/QXYMcx7ZSee7XdHmC+xD7mjYdHLIWgJArLUN1DIsbnO9vxXbRhvl9uI6jyBDGeKuOtk6bMjKssDNkjGAFocJYy0Q3D5MBYe8he5Js/qErvRMyl00MMQnQLolBQtrvdSkrxuK/FgwsIQ==
    KAFKA_SASL_USERNAME: AgB3JxaJpTvC+c3nTs9Dnr1cUBcDL1ECMm2fSSt/SG6a5uPm1XEvsON3TqVuFTM/CiJEVx2YDkISo8PQhLAx+Qa9xZtjHW+lm0mFaYbMwZv/zgWTYHZmYYwQ1pnEf0AvZjwR8YvImIw8XRMhhNv84CUOefBJUPUerBo19yi5QUfix4qwg5A4O9nqMLTJzyCgq2lO741E1PQ3tfbHZUrGUTlRTc225A5tamjLr0JYmgWo/yr3X9FtaQOOeqQLLgFQVuRFbBk2/Lh3CzWJx3r1H5iM8SOdOFJxtMbq52EUoFOfHA3Y9Wj4noqvmfUU9xApGzUVQAemw+CrOVU1eF9LykbQJiGjtNMalNxQReyrk0PRHYhoSGo9T2OTNlwPsF3nS6fmoNmKq64x0tIwW1hbDXZLN1CG3bK1dS4yShvBgSK3e2dvsM+cduPm4sXAG/JDWQ7L58Fh/ulKg3aeCbZDkvA9Ok/VYIU8XDZgdn0OL/hHJ2Xxj8FRggmBhbullhk6etPkDUtV+n6/D2nOg5BeH4exB2q5FAD2OptECFcncHnqPlcB6FNW21CX4Tcg/rP+etf/a5IjQkKW/RtkybybYlWbem0Yg+Z3CjFMR7vdTR0NvJK12tNS9js7hQc4gZeKmtBLzOg/boVEnKI3gXCn7qh6gtRJKNhGkGSaLX/O4pouHjffdwM2uwpu+DnvT8kz6oR2wHFeLaXj/oxouxApWDPr
  template:
    metadata:
      creationTimestamp: null
      name: drova-kafka-secrets
      namespace: drova
