---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-pg-users-creds
  namespace: drova
spec:
  encryptedData:
    DB_URL: AgBh9SLcv3XOswV5f86q5V8GFC94ohGFKKAAoK/IHzNEzHgh6tRteV1xg/em7uDyZFwp2wLSzV/Gq02srtMUz3KJZMEj27xdCLgQqgkpmPJiUgWOWKMAhD0XFjUqFzP5nM2j2L/XPvnUM6TCdLSb9YuZna8liGl2Vtomg2ItWJg0H6baTHEwhbntisEJrcnaS8jMJ39NawfDEta+Jd8DGHanlbeyfokXXx7VsP6Jq4xXUuKlv1RnUwCh66sllveHecGCe5TrMUGC1Z5NSPlp2adHf1tFzNkgB3IVV4Heq/4qHA4vFiojxGa484ajDzQHt2bg1QaqjLwQqIzI7lilQbdzeAa/mICyycUHCpmdRHprUGbqahiErwhyDRewiKJ2a7e+aQz8eTav3LHCtkuKrPhl0gb3eG9vq2tcxka9n7DCQwRKlN2eI26b6Gko9qQpgVFjd8M0lxAn5Hyf7Fv7K3GOv+GmyZaM+azw/wYXBSjI6X1hMJtpDS63MczsKt0LuahOD93SIkuFPcx0OUqPVt/bLJIwrJQloEnH9EvIIOIDz87G57Y3V4/+DvsooZo3DrIW1GwYNVRZgCuMEfvl6QQWg0jZXw64eBa7CR8apaF8zmBgtHdNGVnQo9ujxQCB6IjEwHVOU0+i57+XUzF8mVwmSKr+4jnt94a0n6++S5vNjNIs9IXpO+c7nTmpY34++OGFIbOLbUOi64HJ3JyYZdGF4SwGMsW4Pq+76MtdxG6axHhCBnrC555GJIhyfzcp/fIASd5vXxNHg9bfkjjwrwHP89C0zRJTcb10Mjkte7ixc785m45+eqYDSF4+XMdiFiDcHW7vXGAMkLC9TCfhuNUZkeo8B3fEze1j
  template:
    metadata:
      name: drova-pg-users-creds
      namespace: drova
