---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-redis-secret
  namespace: drova
spec:
  encryptedData:
    password: AgDP294ZhedD+nU/abHU2pT0j/U4y+C2Cnor14hN8sqWidpbT/21qgQ9WrcZDBm4T7e3tjzD7Y/GIvzH9gd6N2c4K05tIixQYWCjLL70Gjwpfj58XGps0Mm7AMECG5IzWJOpS+ODaYxlcdTmWg4UuJTV55ybz9RUp6zNdS/QuRxp6wQRK0f1lYzGle9Z71PNVFkT6hu6gaCDn4hF+RyG9GVtCGuiEcVCHXezHplmSz2I0TEbOPUQiRVZUbZoqAtx7Qw9dUBRlq+NZObUz2OIi/5WS9g+SNtrNT8wLyJEpri4YT73/wirhVXILyOpMAZ7dcHRY5xJjtkWAi3w8fvbeJ+Zo1LA0ymuiT6lCkrJQnGNuzCJYNcYfgtAgKkvGSWD4BxnuwqORqXWfID14cgO1EBfNxEGXtHsB3Z+Lc4+CP6/u6EYCkBvHC+bH8xozNgkrY44WWBRcEJGmWgNYKXvjwascYvsFg28CvMgEKA79ODkdzpV1NKH1pT58vQfK3+mMsVovHu6Nxc3igc+dGLDiHh62Oh5AjA0HVHOQbsNDtjq8OMrXUS+k/F6V3RNPSPwPXiYNq5wgPZMyIsUnQol13BRxu42Q1LlYkaPCS7oZjESWIOCpNOh+sGBmpbqRBH0a5kKhJ2ov65Ro31EXT03H18Mvqjf9W7A4GhIf7hQWDorIWg9SFtqsMTF3JNWHglzndLk5fzgCUwBYKXtX3V/TuF6z2EjtgSJYRHySQ==
  template:
    metadata:
      name: drova-redis-secret
      namespace: drova
    type: Opaque
