---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drova-dispatch-token
  namespace: drova
spec:
  encryptedData:
    GH_TOKEN: AgB1logPa7fTZW0My3y0+p3IqIWTrMUMrRlpwRkLziEzRHtc/AXo9LAbqVQqEKLCcEx4sIaGvEOVU079crPIgIDkGSjsdWMkfLU0eV32vGeXD4dDaYtPFWlGLldT/2JRIBYy+Ggs0BVUvaD6E33IzZUW68KiV13lpCMqi1y1t2ITb1cG02SpPmvnpx2iAnaujnPpXtLVFN5AA9OaNQM26432kfdmGkoEoSuZpBk9fECaqw+5wPXtCjU62g5+A59T9AH2OtXqjxvNoPcDODxbn0iFc338At9AKQQ1uFT/0YY6KvL+2PqdwEzQBJOUjAhiLt3o5Cb9I8QaR19kb4Ra3z8+WDg5hCIlI525yfQG35Th/oAQHWcxcqWlw3i3Xo5H6zB1/t/M8I+G2Y9jrW0/cdfRE5bAX+5whVW32RXoBF+nK1pZPLi10g9Shk520pSLFu92KCfAYeW6xcUoRL3YnGdqNpQtUwyHVvbc5/OfUP2T2MGqBN8yZLZjcT8annpK1nWeYjlEnsXGo3t+e51qLuBdy9WoCtBoo8BTANM+Gg5qKCY47sfBNUg64PqPtNVl2urVIfUlMdiufVe+VhWXtzFtmyO2lF7iBZwY0ymVQ3M3WfUlJ3vfL0730ImdLJIHDBvzKsZoXRXMyEv7iLQju4150pfB8Jtj4hIB5daLP5MCV+xsimWwsJeg/5UFwpsrPLJxXoEssWAYesPpx8p6hVZsX52UGy9Nr2d4rtaiApb4omOsGEe/VNiaQNbdo5a8iLupHLVXlzVtH6duccEdyz7C0iV+G/TJ+kLVFX/uxPOZ3k1Pw34Gt9/kn7zeocw=
  template:
    metadata:
      creationTimestamp: null
      name: drova-dispatch-token
      namespace: drova
