---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-seed-secret
  namespace: drova
spec:
  encryptedData:
    SEED_PASSWORD: AgCJ4dYRdDkKnkpIw0dKPn+gwo7Vp3jcpHPzGVGkYhaqA+HKU0EiP1xoyZc4MT2Xotyr8bJlGetmO+DizrKPAGMmXKI+8F8AEW6gBYAGU0mCX6GUHTLo6PBDKLmKtUHiLMFKxphj7rMjQC0T4ZHIlMzAfo0VuMZqdCAiQOKLhs6svXR6/vnJNm6zSDd6lPTNTPtvWAwlhjiZROGd5LV33dk2ikwyxCrJj3+TxRL+qjkYTMCb4rnAruMAdXN5Op/G1VIMQDbiE4lZ054AcyO0bTQFPpIe0M8FIW5vuA9/+Pwk6gOdzR4wKq3NWPoSZ/p0m57e0fZPLTUpwxdPANiVr4TVUaH9nCgvdmY6tZKNu6ZA6k57t/zfcfHtvcCJ77U+PSRn3GWfp9+fw/EUFVCJ55rFNUG1BUvVC3tX1UnkEfoK+P1X07zCh6mJgGxZZp9oFQEz9bmzhYHWCcmqUyM4hWyydzKCmeVZcmRhJKj5c9fz0FuMeT8ECFN/mzgs315HI9zcb0HPHTSeKT0/5eNGbzFARxIvNfAxgaXERcHmdqeoDCC+fjfHeRpqAFgEdiYmEXmQQJnz3mk0eLN1mz5MaENWToS60baJtKIQz0SgmIgQxD9BTlMUtIMUdfhx1Nnr1e4p10r8R7jum5ggJIp6hLfilvvsnBOyBLVoHPHzSwENq2SWzPwg9U5BH6oGjayXUMWKiJxt9lRyHj+qWYhaekRm51GcH6vZ1Npdr3rSG/gqfExPc/n+sFTMISPS8SZmi1s=
  template:
    metadata:
      name: drova-seed-secret
      namespace: drova
