---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-pg-app-creds
  namespace: drova
spec:
  encryptedData:
    username: AgCHTlPs2XO0ZGT/0ahjG7hBs+RL01/skpCkF0b+RF7eu/cpJHOIYh8X50EkNoXuZN8FhyHf72Fay+d0No09h8iIpaTuvZRakQ+YI/A4TlZA1qMc26wGvPqBIQigTemW87/8KlE3vtDeo33SJ9BWAjDdyGL4ihauXeXbNJ2qRK7h2095ZudJQ6oDWfTl0zy0tFmPPRxnXJeAjgxMCMKU+3A6D1vKB7eEmtHrNuJ10tKTVoacK6Y1amWfxp5QA1dE0WNQiaAXferkLeH0RAdkFpwlcVn7h2tjPY5MzeDUCGyF7PsMPnx9qho35QpiDediiI/oDi6+gQB6hCeOYNEunG6TkB2xCrH9Ir2ASClckEm9luWveWBvCFqVEn6nGjGluiA7hpo0xK7/B9c4T8T1FWxq6HpVwXZx6Itl5GSFete79t/IyC/VmoJFqgBHVX6ny2mZWFkhZjXh1AtVivPXhqc2V3kZYmY+VtftsX5cMb5+09urSJK89xX+U1GWsDFD7K/lXG11/fVYWnvudKNZHX1vJpgitQyj7SjW3UN0RS//HX/mcO5dxVcZ1AR1uRNLYv07jwXB3izJHnrmRYq00mjMXIKb+FCSkwoH7H5mIvXkihfrpLQLwXW4rNO3Fudvvf7YTIj1G1Rxf+4uJiEHCPFVSBnlNWEOOyJ2GSz5yBFI4UAAT6GBN5HGlwc4zyw5GkW6FAkGnTzqonRd2A==
    password: AgBxOLhPhBXcamraBsJILrNpK12jWIwMkvbGWq6U+APw3YwiucyXXVBn1FyCL7hodTbFZwlSeax+tolY1DP0D5jMrwZ+02ZvHdbyFLtqu1n9Ooy5hLmOrtCWORXo6tCCBFGFCVCQYkUfFyiY0ThYFq7hdoFi51/8B5RmIH1FP2ZUm+QVtpRA5P34sAL9qbwr4AiCQ7YHhX3T3E5QJCZDK0m3/kSQrrKiAIeQMqbCErxW6Y+z+ipN9ry1q5uC2ltbuf2JrlWSUfHFG2cHCFeXC9ONY/WwUXX6ZLcKszQzrEYoSXcgCDYVPGTGbs7oqNjNK3VbLAE9zr8Vi3zpT/fIItZq9H0li0cXw2un2GMEoQtnUQMQH8hesJZrHagkTYtXaZhzYRMliKlQMMOU8AtJP7ly5c/dD5/C7U4njrzyMwZjFd3twKJpYE8jZ60ytnF5W0sGxQJaRWiUkiUqbn6/R2VUBXPOccrWchcuF/vY+h4wpxnEf6pdbLW3oLSC8/Ey4iw+VbpKdzcbmUS4VW+iJ+Vnt0VoA9lBoavicqiYI0RpOi4Fpwx8ba0LtkqxQrC0ayTjkPLQFFeKpMdGVwYlCwZsgnL2WjgFDMcmv7ku+kqpBorK4W36RgesGoM7B/H/6Ww8seWi1eg4JRCmuvPvGk3fjRE6XySFZBsCKf3TlEZvkNb/TfJ5ejFM6z5D0Tz0Rj6ngqRYS7XFi56zptMhfZr/vpSl5XQ2rg==
  template:
    metadata:
      name: drova-pg-app-creds
      namespace: drova
    type: Opaque
