---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-seed-secret
  namespace: drova
spec:
  encryptedData:
    SEED_PASSWORD: AgBQ0fUgVUkuZV6QBSleqyGFoVifFHT99FPxIDNLPrC2o3qFV9zlpn6355bGtAzLQ/2GUvozqYK5Rb+I0UTDx4AYfP7XOzT6Ay7O9OYaZX6PB4HTf/D2fOLFkRVusl82+upOzwqWTsnWqWxxCljbDTMCSfYap2xkCmOsKPIqQH8D16KKiAsg33mxjx20rRfNEb+UrvWVo7CSYCd/SW8uD8Wk9UuO8gz1rqUfV9nFvy9OGEToONz0ZUtTalxQgTKxf8OAbB1CiWV1dQK5c6pElIv/UQnQCOLKToO+019vv9Q23P3c1aDgnd8wHIWw/0mbvIBV0LZ3w4ANFAjC2hOTMoZvfAGqzSBiuJH+rQzBAWTlVcoQysOaTMmZ2zu7wjNcFJ2GL0YmmvXakqc1pHA3qGSjjTj6NDSY4y9OgEO+45HvOxwBFxQBzSTG7XJD0hEvfC3clAwoxbnwJcWhiDwwz6cts8Sgwf89hmcxIpW6SALQq+P7bt3nRn9B98mXOXDFTrsE/DcvPFsgPQQaCQn1s8oKGhLdJNrJt1v5Jdq+9yilumfa2zZtYdr7NFa+pilAkesU0JGubV1Igd7RC2WBhBopCM1JJ5EOi4xGaafqsKPT2Bi50m1QMJmD1IExpoVIwd8Yv1toQkDHHlqRVtOEN1oGgc+s3YWTEN9h5cxB9Wtfm0MEQz95HuId+QFblX18TEY2bXe1Dqh6ct4=
  template:
    metadata:
      name: drova-seed-secret
      namespace: drova
