---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-pg-trips-creds
  namespace: drova
spec:
  encryptedData:
    DB_URL: AgA4nQXKQ5bx0miaO9Cyn9ObT6sAo4tGC1eHvxU0L58fwFJJSgYb0WMyqxMQdkyChVoZ4oI3hhMDy/G8x8jxRhh/sJaT4Gqgd1CNtSj10WUV/G1mf0a861DUVYb6I0R7maH+ge7hMaFF/XapOhe41v//tN6E5ifoAZKfpox9aCj9t3ie9rL1zgRZXJshYWa36MpgrasLGbpfdVTbkMN8L7b/egEgQMDa1dfsC26kpKOFbTvlznKEhPC43Axzl2FBFEbXtwBd7OQiW8xehmaL8C/sWcMiNrqdY2OOk42dSCbp6TWpah1MNr6A3BlUnduPKS0GyU3qmoKUa1QpNEhuOixUhb1p+RRUWDs26Pj0E5z9wJKTuwzg/MBTECQMQZsa2fdXdhUl7Yh1oUKTfBUaQuR7i0U5saR2uUVA4LEdBKQ04wF9UyJBxUj93252war8VYkRdFKPgs8jZG0Rrq5iFRoZHwXeq0jp9gV1mjoNfqDhpJjt6xRCj6dprxnzEKm8EbJkBDRjftH4GewFRa+io7Mju3k6pJ/UdnNHykOhh3bv6cPCHnkHWndLkhTxL6FuESmxmKAeR6TkXM0PABgNLjYX6P4nWmKF6PSW42On0s1N8WeEeVl3QBPl6V1kQHingno6mY7bhV+XuzN0JDnwcimLGvuUKifWRMe2dAhWbLEcEbS112RwWbcCwHwiL0JAdDJHDfTdyMnzXrlf396DfLAIZgVPjXi2T/R9+GDRE8iY1VgcLjyOIjGOnCNWc5I6VHY+XJonNICLimdLgwxju77jw8+w9xWDtkh+bh9VhUKNVHzRTMax9yIDOA2Cj4PKai7i3/1tajhyMOakDjLltKQznwr6NPis08mc
  template:
    metadata:
      name: drova-pg-trips-creds
      namespace: drova
