---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-dispatch-token
  namespace: drova
spec:
  encryptedData:
    GH_TOKEN: AgAVZx8ufEtwrCIDb2Qe+lTive8fMcPDqP4HM1Su1fvT0ZhTd739ujwKn9pgwAo7XdwvOdeVUn+RrYRLoiiVDBMSj9v52YSA2FCzgVMkMJ4/NUxnKgxyj9MNtcY0N4vTcCq5VqHqi53zzgQmPKxRVmUC9BTFwB1GCZxJnzOIMtBeyjXKCNUWgrMSFI8vgBNZeuCGcAph2CIeidNpxmQn2ixXUPf2d4mhSwxX4Uk1ra9KrMF1dC7GkAVsY56jvAlyc/aUhJq+QzXWlZp9RtvUDBUuFki5CKWnGBfl3fvbk+TKrcXw4MtNCpwFyelzIkKZAdz0jdUuIKAV5bl/p0aZRgPmuZPLzBPQB9e6a4YK2jjpUrToSXU1U7Y4yr9oz/8sttqmcrgzoj/qcEtbAFy/raGCVw1FpZLIBrRl6kWRAAWjoPFO5NoYJ1mt979+5VZHc2hWd0z3UB2A9Oq1i8ryZglcyobz3gB+y3H3W7z/e8L7qF1lLh3UG4rRRHtje8XQWROY/GBv4Id+MP7iV5G0ZIHsJFxgxFxRSN5zdGr3Rea5tuSQI9cETzR3IaO1eVw8Zm5pECAkCP3S+EQd6eXMlMAOqgO2XCA/FyLAtOD1BqOagmsHIEuk12AN+1RxL4QeKnSK7rPloHDLbEi2D/ffYYSxrNTUcHQDBGWn6j0cAV+xyb32H1rUWSH9RysiLdk2UBGgsaG96NmvFxburHA4P0ixc3e0YarYvwKQMNm3EI2BSMrDjG0RzBoP9Tht/sOo+le+fOeymOEQIBLN70ksQDqVWaUhM38apFHsaHJxH20q2vDI7NMQzcLaLlvi8fo=
  template:
    metadata:
      name: drova-dispatch-token
      namespace: drova
