---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-redis-secret
  namespace: drova
spec:
  encryptedData:
    password: AgBut2VXSyGNA4IFIW6nv9SFei//xwR4rAZFgPJ04W/JhtUA31XIDEkawcsV2bJ8o53e4tEL97UMt/dunybdlUIe9o6Sx4IYmlpli6NthTBWs/ws3nRPBIcZ8LEsMk9hCbW0QaVtSvpJbNadd0ycyPxoGrqRbuo+lANad4KJohTcIr75oHjf7dkZ4PhU1LwFbi5Hk0Sl1aC4RmwGKdyqAtFL8/ItqFJJdoJx8VNZ7EyOHkol5qtEQ86rD2tyvPatny6z6KS5yF+q+aT7iVt/NDlHDDlC9pQTLSvCDwKW5gAAiUXRphtWfYUzRQ0Sn7mtGGvIoi+qb1lAGdzhoqHA26iT+sjVB27A+CUIMaDiYgQf65u0KQnKj12A760BYUwAkb05Yjlkql58vgh7q3+3DnAo4c79BCEPWlFkOBYI9Bnz8zZo6rH24+3sTTc3X0iQFyV7E59p0H9Cvv1BYspsh5MW88kKZrGkBH/huUlw54xSTcXmZXTRxY8M0Q3J9307GfoZ0tLZkQ1LzvO8kBDfIaUuzl8NZKyJSSWx6W5D5ViOxEyx3JDcAyXy8d8tlCkkXksISZUI6vKjr7X6kjkZGh7mSGa6jjncwHqOrpKKUYiLxvW/+x3rQiw7qH+ALspxT/J7SA8WZkEDWH8nNjPTbsvqef2b3NfK+OO4cGPeIW13FJlhn2kodnm1/ilt2CLhN37tCvZeLOXZfGuy93yA3bI+eeL8/M+4IqTSyg==
  template:
    metadata:
      name: drova-redis-secret
      namespace: drova
    type: Opaque
