---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-seed-secret
  namespace: drova
spec:
  encryptedData:
    SEED_PASSWORD: AgAi+f5g3GuFEZVhlTSqZSrtFsffdslIgbCljlKBlWzl2s8UjUxtI9/Mk1ExMcSfVUvsna2JyzqTklmSLwBMUYEPLCkNEpjmeyDjuEQblaHrXVUKK4IuikWFzpoD2GpRPw/hC/lpZb4tkCqqvwR81Vg+PSFTquxX7aOIQc1jJ4FMFPkmWleMXqz17Q4kWHqStE1Tq6vC30P9wdC7OYsJb3SCLmGXor35f5dkQM04CvBatcMhe9hR3UJT7Y3SpSzoVW6+xtayap6b6UxzZlrBCbhnrfsftBp8ZZLQi0SnHKxveEUMQzBwD5+HOZrCCbqv/Oo2j+8CtKQChJe36YIC7zkwW6pBTwoyYRivF2Gia2KWHmIF+o+ttM8Z5PZRzfc4ScMVrQBD/geHqbGYtlRAVGCHiq7zw79IE4C1v0JruafMWxXxq1vVrLvvnDnrVNwIfcvOk7LjRSYad3xCpyst8NVegQlcG1aRsUk0R4SSxJawjNLJGN8Iw46alb8jdvoCQHksnh8BWfoRvswB0U7fcthEpMVwzoFvvGZ10ySEX1FUmnkAanSpT8KfnFuldsf6DF+EqWMfsQJv5eQIoXABVccEOkaxoXBhzljzVuaD0WqdrDmRgGMQrpdsaVBdOO0aH6oeuvBgejkuyG4ZkUNFFY7I21g9uBX1kCRljfaDeGu2xDr7G21Eou+EHZy9lM8N/r1ChYiqbV31hL8=
  template:
    metadata:
      name: drova-seed-secret
      namespace: drova
