---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-pg-app-creds
  namespace: drova
spec:
  encryptedData:
    password: AgA1G+du9tuRZNmlPNHKbQZYIyLkUhY80NY8L5H1m8w4szm7WAIcrHPxSFZy9bukywN6WxEOhyLaraedRzwukTGNmfmEAyvg+RZRVbWs58MBIlYa/kdCPamRjtaYmVSkC+ejWbxX3tpJh7KzG+10O7iXWJrkyGIKR4f7b5Z9BSF7zBpVpqvXKILrRr+kXZbSMn9meamJQnvjsWG6u+FJpy3H7tr5WfR171cJBXpekM1GD5BVCiWknP9CoPG/lWPVCbRrzWfyYRUFZBosoT9lZ7bLE+h79p3a7Ojf0kLwWpoJ9T9c96yJZNSqvxSqqk/D3ZKd4pyNdR6M5YvJOp5Hl5OP5mNeWPFhAGOVtjoqqT5QUMJXr7vzWZROp1zooVAzWfP7gFomnkFl94qzSAaZ97BhlQZ9iGn03ppLgK/LLfae6FV3AAt6sSXaNMTngvESJb0/5mHNMTkx8bVsiYVIxB1ennXSw5VswiLaeCFvrhNPuDJVPoYhzdmM7u+WcIngBvHNxiv9TRl9Q+VvOtK/GbVfdomRdntIBdEpXXsG5avJQj9vgTXhmoX6KRJQ73bJ7GsHVZZOjFwd7IlAZcNS9JToFAHvUGhX1tcoWSf/bcXI66BSsfGXHZw8PfqVRWi8LxrBPPbns5KTdRh/v1MVf6UYvIHLmi8ZS68/CxvlH0F2DckzXvTu27QWO1rz6X8KUqi6lNrHCS/dQ6wGkoXATMQcxe1JBqwJMA==
    username: AgDgHr+YW8pRmNiJIJZso+wxMn2CjcL+wu4mHle/N4qay+ytVnTqoLD8te8AUY0ms8ndj4uKYjjdChYGIoWMONM+guFSG3NqwLI1jZwIzF9rp6bInJ32/czK4ndzRop8wrhhtA2XLeVq1UPnPByeaj+3WVgXCukZuKw6e9wLwCLab7u1lw+uzlLFKRhLGCivefWd2afESO3P9GsiWQjalixQGvHpCouHSh1Y0SPzV8aJSZHyIRFoy/EjPYXVmFyH3xB10qGW78GDyEc3YKMFFFbUWRiQRZsWVn6Q84qaC78LDJYzBLniam5ryc0+QwsPQsBqGWiIl6/5D3krqfGK0yuH+pHsA/mR8B9iCyvtb8Iwl1nuBfWSbeqlo3zbNJ7AZQS37o+NSXsFMJHBBLu5GBjNGj5KtletL1wCeG76rVU9irNbpxeZWs9q52QtPCh6tXKXm9b0oqWbm9ORXYFntO3Urx1D3uGTDa0sXhMbuhx+Pj8AH+bJHXyWlNSgj6OWLUSv9DFLYnwwBPH/QCDveGycxT+7TGuphbKUfm8H7umU0hKlJL2UQgrIZkP2yDE26xd7Y713YupYfA/a2gwm+UYuJ4Ciu7w6mzSqTB15qTicmRL7r8SD14+fVCrGjW+vptSzBIw+KlwvteGWyk8jHHjYPonHygjNMXtLfewK52cymWcoPDpyYoPNL4P97PXrCt8fDlhMO14N2u4i5A==
  template:
    metadata:
      name: drova-pg-app-creds
      namespace: drova
    type: Opaque
