---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  name: api-gateway-stable
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8081
      targetPort: 8081
