---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-app-secrets
  namespace: drova-staging
spec:
  encryptedData: {}
  template:
    metadata:
      name: drova-app-secrets
      namespace: drova-staging
