---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-redis-secret
  namespace: drova-staging
spec:
  encryptedData: {}
  template:
    metadata:
      name: drova-redis-secret
      namespace: drova-staging
