apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: REPLACE
  namespace: drova-staging
spec:
  encryptedData: {}
  template:
    metadata:
      name: REPLACE
      namespace: drova-staging
