apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-pg-payments-creds
  namespace: drova-staging
spec:
  encryptedData: {}
  template:
    metadata:
      name: drova-pg-payments-creds
      namespace: drova-staging
