---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: drova.retry.1
  labels:
    strimzi.io/cluster: drova-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: "600000"     # 10 min — 1 min delay + margin
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: drova.retry.2
  labels:
    strimzi.io/cluster: drova-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: "1800000"    # 30 min — 5 min delay + margin
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: drova.retry.3
  labels:
    strimzi.io/cluster: drova-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: "7200000"    # 2h — 30 min delay + margin
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dead.letter.queue
  labels:
    strimzi.io/cluster: drova-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: "604800000"  # 7 days — DLQ held for manual inspection
    cleanup.policy: delete
