apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platform/schema-registry
  - services/api-gateway
  - services/user-service
  - services/trip-service
  - services/driver-service
  - services/payment-service
  - services/chat-service
  - services/frontend
